// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzyOWHC0oP11_wDHhxIquTG5pjD0RKQ2s',
    appId: '1:612428675062:android:bc93fad0d11d715a53f9d7',
    messagingSenderId: '612428675062',
    projectId: 'kusistant-cf6fa',
    storageBucket: 'kusistant-cf6fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4XVmB9YfhqMN-tHvLSBvdTypSnYElurk',
    appId: '1:612428675062:ios:6664a4cc3642cf1d53f9d7',
    messagingSenderId: '612428675062',
    projectId: 'kusistant-cf6fa',
    storageBucket: 'kusistant-cf6fa.appspot.com',
    iosClientId: '612428675062-vkn1rm97m8lfi39qmfbda02ske20t8fi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterwebview',
  );
}
